name: MLOps CI Pipeline

# 1. ¿Cuándo se activa este robot?
on:
  push:
    branches: [ "master", "main" ]

# 2. ¿Qué tareas (jobs) va a realizar?
jobs:
  code-quality:
    runs-on: ubuntu-latest # Se ejecutará en un servidor Linux gratuito de GitHub
    
    steps:
    - name: 1. Traer el código del repositorio
      uses: actions/checkout@v3

    - name: 2. Configurar el entorno Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 3. Instalar herramientas de auditoría
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: 4. Ejecutar Linter (Auditoría de sintaxis y buenas prácticas)
      run: |
        # Esto buscará errores críticos de sintaxis o variables no definidas
        # Si encuentra un error grave, el pipeline fallará en rojo.
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics